node {
      stage ('Build'){
	  if (env.BRANCH_NAME == 'master') {
		sh 'ls -lha'
		sh 'docker run --rm -v "${PWD}/sources" python:2-alpine python -m py_compile add2vals.py'
	}
 	  else if (env.BRANCH_NAME == 'develop') {
		sh 'ls -lha'
		sh 'docker run --rm -v "${PWD}/sources" python:2-alpine python -m py_compile calc.py'
	} else {
                        error "BRANCH TIDAK DIKETAHUI"
                    }
      }
}
